package com.example.sportapplication.domain.entity


data class Match(
    val matchId: Long,
    val countryId: Int,
    val countryName: String,
    val leagueId: Int,
    val leagueName: String,
    val matchDate: String,
    val matchStatus: String,
    val matchTime: String,
    val matchHometeamId: Int,
    val matchHometeamName: String,
    val matchHometeamScore: Int,
    val matchAwayteamName: String,
    val matchAwayteamId: Int,
    val matchAwayteamScore: Int,
    val matchHometeamHalftimeScore: Int,
    val matchAwayteamHalftimeScore: Int,
    val matchHometeamExtraScore: Int,
    val matchAwayteamExtraScore: Int,
    val matchHometeamPenaltyScore: Int,
    val matchAwayteamPenaltyScore: Int,
    val matchHometeamFtScore: Int,
    val matchAwayteamFtScore: Int,
    val matchHometeamSystem: String,
    val matchAwayteamSystem: String,
    val matchLive: String,
    val matchRound: String,
    val matchStadium: String,
    val matchReferee: String,
    val teamHomeBadgeUri: String,
    val teamAwayBadgeUri: String,
    val leagueLogoUri: String,
    val countryLogoUri: String,
    val leagueYear: String,
    val fkStageKey: String,
    val stageName: String,
    val goalscorers: List<Goalscorer>,
    val cards: List<CardInfo>,
    val substitutions: SubstitutionsList,
    val lineup: LineupList,
    val statistics: List<Statistic>,
    val statisticsInFirstHalf: List<Statistic>,
)
