package com.example.sportapplication.domain.entity


data class StandingTeam(
    val countryName: String,
    val leagueId: Int,
    val leagueName: String,
    val teamId: Int,
    val teamName: String,
    val overallPromotion: String,
    val overallLeaguePosition: Int,
    val overallLeagueMatches: Int,
    val overallLeagueWins: Int,
    val overallLeagueDraws: Int,
    val overallLeagueLoses: Int,
    val overallLeagueGoalScored: Int,
    val overallLeagueGoalsConceded: Int,
    val overallLeaguePoints: Int,
    val homeLeaguePosition: Int,
    val homePromotion: String,
    val homeLeagueMatches: Int,
    val homeLeagueWins: Int,
    val homeLeagueDraws: Int,
    val homeLeagueLoses: Int,
    val homeLeagueGoalsScored: Int,
    val homeLeagueGoalsConceded: Int,
    val homeLeaguePoints: Int,
    val awayLeaguePosition: Int,
    val awayPromotion: String,
    val awayLeagueMatches: Int,
    val awayLeagueWins: Int,
    val awayLeagueDraws: Int,
    val awayLeagueLoses: Int,
    val awayLeagueGoalsScored: Int,
    val awayLeagueGoalsConceded: Int,
    val awayLeaguePoints: Int,
    val leagueRound: Int,
    val teamBadgeUri: String,
    val fkStageKey: Int,
    val stageName: String,
)